"""initial schema

Revision ID: 9a5403128344
Revises: 
Create Date: 2026-07-13 20:50:41.708988+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a5403128344'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('firm_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_reference', sa.String(length=255), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('from_state', sa.String(length=40), nullable=True),
    sa.Column('to_state', sa.String(length=40), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("actor_type IN ('firm_user', 'system', 'ai_agent', 'pm', 'vendor', 'lender')", name=op.f('ck_audit_entries_audit_actor_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_entries'))
    )
    op.create_index(op.f('ix_audit_entries_created_at'), 'audit_entries', ['created_at'], unique=False)
    op.create_index('ix_audit_entries_entity_type_entity_id_created_at', 'audit_entries', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_entries_firm_id'), 'audit_entries', ['firm_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_property_id'), 'audit_entries', ['property_id'], unique=False)
    op.create_index('ix_audit_entries_property_id_created_at', 'audit_entries', ['property_id', 'created_at'], unique=False)
    op.create_table('firms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firms'))
    )
    op.create_table('firm_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_firm_users_firm_id_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firm_users')),
    sa.UniqueConstraint('firm_id', 'email', name='firm_user_email_unique_per_firm')
    )
    op.create_index(op.f('ix_firm_users_firm_id'), 'firm_users', ['firm_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_portfolios_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_portfolios_firm_id_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('firm_id', 'name', name='portfolio_name_unique_per_firm')
    )
    op.create_index(op.f('ix_portfolios_firm_id'), 'portfolios', ['firm_id'], unique=False)
    op.create_table('vendors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state_region', sa.String(length=80), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_vendors_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_vendors_firm_id_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index(op.f('ix_vendors_firm_id'), 'vendors', ['firm_id'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('properties',
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state_region', sa.String(length=80), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='US', nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("property_type IN ('office', 'retail', 'industrial', 'multifamily', 'mixed_use', 'other')", name=op.f('ck_properties_property_type_valid')),
    sa.CheckConstraint("status IN ('active', 'inactive', 'sold', 'under_construction')", name=op.f('ck_properties_property_status_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_properties_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_properties_firm_id_firms')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_properties_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_index(op.f('ix_properties_firm_id'), 'properties', ['firm_id'], unique=False)
    op.create_index(op.f('ix_properties_portfolio_id'), 'properties', ['portfolio_id'], unique=False)
    op.create_table('firm_user_roles',
    sa.Column('firm_user_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'user')", name=op.f('ck_firm_user_roles_firm_user_role_role_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_firm_user_roles_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_firm_user_roles_firm_id_firms')),
    sa.ForeignKeyConstraint(['firm_user_id'], ['firm_users.id'], name=op.f('fk_firm_user_roles_firm_user_id_firm_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_firm_user_roles_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firm_user_roles')),
    sa.UniqueConstraint('firm_user_id', 'property_id', 'role', name='firm_user_role_unique')
    )
    op.create_index(op.f('ix_firm_user_roles_firm_id'), 'firm_user_roles', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firm_user_roles_firm_user_id'), 'firm_user_roles', ['firm_user_id'], unique=False)
    op.create_index(op.f('ix_firm_user_roles_property_id'), 'firm_user_roles', ['property_id'], unique=False)
    op.create_table('invoices',
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('proposed_vendor_id', sa.Uuid(), nullable=True),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('proposed_property_id', sa.Uuid(), nullable=True),
    sa.Column('property_match_signal', sa.String(length=40), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('bill_to_entity', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=120), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('on_hold_reason', sa.String(length=2000), nullable=True),
    sa.Column('rejected_reason', sa.String(length=2000), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('extraction_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extraction_failure_reason', sa.String(length=2000), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('pages_extracted', sa.Integer(), nullable=True),
    sa.Column('validation_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duplicate_of_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('source_message_id', sa.String(length=998), nullable=True),
    sa.Column('intake_source', sa.String(length=40), nullable=False),
    sa.Column('intake_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_extracted_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_field_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_provider', sa.String(length=60), nullable=True),
    sa.Column('ai_model_id', sa.String(length=120), nullable=True),
    sa.Column('ai_schema_version', sa.String(length=20), nullable=True),
    sa.Column('raw_extraction_ref', sa.String(length=500), nullable=True),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("category IN ('operating', 'non_operating', 'construction_draw')", name=op.f('ck_invoices_invoice_category_valid')),
    sa.CheckConstraint("extraction_status IN ('queued', 'processing', 'completed', 'failed')", name=op.f('ck_invoices_invoice_extraction_status_valid')),
    sa.CheckConstraint("intake_source IN ('email_graph', 'manual_upload')", name=op.f('ck_invoices_invoice_intake_source_valid')),
    sa.CheckConstraint("status IN ('extraction_review', 'approved', 'on_hold', 'rejected')", name=op.f('ck_invoices_invoice_status_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_invoices_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['duplicate_of_invoice_id'], ['invoices.id'], name=op.f('fk_invoices_duplicate_of_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_invoices_firm_id_firms')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_invoices_property_id_properties')),
    sa.ForeignKeyConstraint(['proposed_property_id'], ['properties.id'], name=op.f('fk_invoices_proposed_property_id_properties')),
    sa.ForeignKeyConstraint(['proposed_vendor_id'], ['vendors.id'], name=op.f('fk_invoices_proposed_vendor_id_vendors')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_invoices_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('firm_id', 'source_message_id', name='invoice_message_id_unique_per_firm')
    )
    op.create_index('ix_invoices_firm_extraction_status', 'invoices', ['firm_id', 'extraction_status'], unique=False)
    op.create_index(op.f('ix_invoices_firm_id'), 'invoices', ['firm_id'], unique=False)
    op.create_index('ix_invoices_firm_status', 'invoices', ['firm_id', 'status'], unique=False)
    op.create_index('ix_invoices_firm_vendor', 'invoices', ['firm_id', 'vendor_id'], unique=False)
    op.create_index(op.f('ix_invoices_property_id'), 'invoices', ['property_id'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_table('property_contacts',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_role', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_property_contacts_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_property_contacts_firm_id_firms')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_contacts_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_contacts'))
    )
    op.create_index(op.f('ix_property_contacts_firm_id'), 'property_contacts', ['firm_id'], unique=False)
    op.create_index(op.f('ix_property_contacts_property_id'), 'property_contacts', ['property_id'], unique=False)
    op.create_table('property_entities',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_property_entities_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_property_entities_firm_id_firms')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_entities_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_entities'))
    )
    op.create_index(op.f('ix_property_entities_firm_id'), 'property_entities', ['firm_id'], unique=False)
    op.create_index(op.f('ix_property_entities_legal_name'), 'property_entities', ['legal_name'], unique=False)
    op.create_index(op.f('ix_property_entities_property_id'), 'property_entities', ['property_id'], unique=False)
    op.create_table('invoice_attachments',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('attachment_ref', sa.String(length=500), nullable=False),
    sa.Column('attachment_type', sa.String(length=40), nullable=False),
    sa.Column('upload_source', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('derived_from_id', sa.Uuid(), nullable=True),
    sa.Column('annotation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("attachment_type IN ('original', 'annotated')", name=op.f('ck_invoice_attachments_invoice_attachment_type_valid')),
    sa.CheckConstraint("upload_source IN ('email', 'manual_upload', 'system_generated')", name=op.f('ck_invoice_attachments_invoice_attachment_source_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_invoice_attachments_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['derived_from_id'], ['invoice_attachments.id'], name=op.f('fk_invoice_attachments_derived_from_id_invoice_attachments')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_invoice_attachments_firm_id_firms')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_attachments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_attachments'))
    )
    op.create_index(op.f('ix_invoice_attachments_firm_id'), 'invoice_attachments', ['firm_id'], unique=False)
    op.create_index(op.f('ix_invoice_attachments_invoice_id'), 'invoice_attachments', ['invoice_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_invoice_line_items_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_invoice_line_items_firm_id_firms')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items'))
    )
    op.create_index(op.f('ix_invoice_line_items_firm_id'), 'invoice_line_items', ['firm_id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('property_patterns',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('pattern_type', sa.String(length=40), nullable=False),
    sa.Column('pattern_text', sa.String(length=500), nullable=False),
    sa.Column('learned_from_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('confirmed_by_user', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("pattern_type IN ('bill_to_entity', 'project_alias', 'job_name', 'address')", name=op.f('ck_property_patterns_property_pattern_type_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_property_patterns_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_property_patterns_firm_id_firms')),
    sa.ForeignKeyConstraint(['learned_from_invoice_id'], ['invoices.id'], name=op.f('fk_property_patterns_learned_from_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_patterns_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_patterns'))
    )
    op.create_index(op.f('ix_property_patterns_firm_id'), 'property_patterns', ['firm_id'], unique=False)
    op.create_index(op.f('ix_property_patterns_property_id'), 'property_patterns', ['property_id'], unique=False)
    op.create_table('vendor_patterns',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('pattern_type', sa.String(length=40), nullable=False),
    sa.Column('pattern_text', sa.String(length=500), nullable=False),
    sa.Column('learned_from_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('confirmed_by_user', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("pattern_type IN ('literal_email_sender', 'literal_company_name', 'regex')", name=op.f('ck_vendor_patterns_vendor_pattern_type_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_vendor_patterns_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_vendor_patterns_firm_id_firms')),
    sa.ForeignKeyConstraint(['learned_from_invoice_id'], ['invoices.id'], name=op.f('fk_vendor_patterns_learned_from_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_patterns_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_patterns'))
    )
    op.create_index(op.f('ix_vendor_patterns_firm_id'), 'vendor_patterns', ['firm_id'], unique=False)
    op.create_index(op.f('ix_vendor_patterns_vendor_id'), 'vendor_patterns', ['vendor_id'], unique=False)
    op.create_table('approval_records',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('markup_attachment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("action IN ('approved', 'rejected', 'on_hold', 'hold_released')", name=op.f('ck_approval_records_approval_action_valid')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['firm_users.id'], name=op.f('fk_approval_records_actor_user_id_firm_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['firm_users.id'], name=op.f('fk_approval_records_created_by_id_firm_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], name=op.f('fk_approval_records_firm_id_firms')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_approval_records_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['markup_attachment_id'], ['invoice_attachments.id'], name=op.f('fk_approval_records_markup_attachment_id_invoice_attachments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_records'))
    )
    op.create_index(op.f('ix_approval_records_firm_id'), 'approval_records', ['firm_id'], unique=False)
    op.create_index(op.f('ix_approval_records_invoice_id'), 'approval_records', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_records_invoice_id'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_firm_id'), table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index(op.f('ix_vendor_patterns_vendor_id'), table_name='vendor_patterns')
    op.drop_index(op.f('ix_vendor_patterns_firm_id'), table_name='vendor_patterns')
    op.drop_table('vendor_patterns')
    op.drop_index(op.f('ix_property_patterns_property_id'), table_name='property_patterns')
    op.drop_index(op.f('ix_property_patterns_firm_id'), table_name='property_patterns')
    op.drop_table('property_patterns')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_firm_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_invoice_attachments_invoice_id'), table_name='invoice_attachments')
    op.drop_index(op.f('ix_invoice_attachments_firm_id'), table_name='invoice_attachments')
    op.drop_table('invoice_attachments')
    op.drop_index(op.f('ix_property_entities_property_id'), table_name='property_entities')
    op.drop_index(op.f('ix_property_entities_legal_name'), table_name='property_entities')
    op.drop_index(op.f('ix_property_entities_firm_id'), table_name='property_entities')
    op.drop_table('property_entities')
    op.drop_index(op.f('ix_property_contacts_property_id'), table_name='property_contacts')
    op.drop_index(op.f('ix_property_contacts_firm_id'), table_name='property_contacts')
    op.drop_table('property_contacts')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_property_id'), table_name='invoices')
    op.drop_index('ix_invoices_firm_vendor', table_name='invoices')
    op.drop_index('ix_invoices_firm_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_firm_id'), table_name='invoices')
    op.drop_index('ix_invoices_firm_extraction_status', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_firm_user_roles_property_id'), table_name='firm_user_roles')
    op.drop_index(op.f('ix_firm_user_roles_firm_user_id'), table_name='firm_user_roles')
    op.drop_index(op.f('ix_firm_user_roles_firm_id'), table_name='firm_user_roles')
    op.drop_table('firm_user_roles')
    op.drop_index(op.f('ix_properties_portfolio_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_firm_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_firm_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_portfolios_firm_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_firm_users_firm_id'), table_name='firm_users')
    op.drop_table('firm_users')
    op.drop_table('firms')
    op.drop_index('ix_audit_entries_property_id_created_at', table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_property_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_firm_id'), table_name='audit_entries')
    op.drop_index('ix_audit_entries_entity_type_entity_id_created_at', table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_created_at'), table_name='audit_entries')
    op.drop_table('audit_entries')
    # ### end Alembic commands ###
